background{White}
 /*
camera {  angle 25
		  location<0,175,350>   
		  look_at<0,10,0>    
		  rotate  <90, 0, 0>
		  //rotate  <0, 0, 140> 
		  translate <0, -10, 30>
		  rotate  <0, 0, -40> 
		  }

//top view
*/		  
camera {  angle 25
		  location<0,0,350>   
		  look_at<0,20,0>    
		  //rotate  <90, 0, 0>
		  //rotate  <0, 0, 140> 
		  //translate <0, -10, 30>
		  //rotate  <0, 0, -70> 
		  }

		  		  